"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, HelpCircle } from "lucide-react";

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState(0);

  const faqs = [
    {
      question: "Where do we receive our login credentials?",
      answer:
        "Team accounts and individual secret activation keys are pre-generated by the competition organizers. Desk credentials and passcodes are distributed securely at the registration check-in before the opening bell.",
    },
    {
      question: "Can multiple team members log in from different devices simultaneously?",
      answer:
        "No. Under the Single-Device Desk Lock protocol, each registered team is strictly bound to exactly one physical device terminal. Attempting to log in from a secondary laptop or phone will trigger a desk-lock rejection, ensuring all desks compete under equal operational conditions.",
    },
    {
      question: "How does the Director Login Approval process work?",
      answer:
        "When your desk submits its team credentials and unique secret activation key, an authorization request is dispatched to the Admin Command Center in real time. Once the Competition Director confirms your desk, your terminal unlocks automatically.",
    },
    {
      question: "What happens if our device temporarily loses internet connection?",
      answer:
        "All portfolio holdings, cash balances, and executed orders are recorded continuously in the atomic exchange database. Reconnecting immediately restores your live portfolio with zero lost inventory or duplicate orders.",
    },
  ];

  const toggleFaq = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section
      className="relative w-full py-24 md:py-32 px-5 sm:px-8 lg:px-12 border-t border-border-brown/40 overflow-hidden"
      id="faqs"
    >
      <div className="max-w-3xl mx-auto flex flex-col gap-12">
        {/* Section Header with Scroll-triggered Fade */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.6 }}
          className="flex flex-col items-center text-center"
        >
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-maroon-subtle/80 border border-border-brown/80 backdrop-blur-md shadow-xs mb-4">
            <HelpCircle className="w-3.5 h-3.5 text-accent-green-bright" />
            <span className="text-[11px] font-mono tracking-widest uppercase text-cream-light font-medium">
              Competition Knowledge Base
            </span>
          </div>

          <h2 className="font-serif text-3xl sm:text-4xl text-cream-light font-normal tracking-tight mb-3">
            Frequently Asked Questions
          </h2>
          <p className="text-cream-muted/80 text-base max-w-md font-normal font-sans">
            Essential operational and technical guidelines for participating trading desks.
          </p>
        </motion.div>

        {/* Clean Accordion with Scroll-based Entry */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.15 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="divide-y divide-border-brown/40 border-y border-border-brown/40"
        >
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div key={faq.question} className="py-5">
                <button
                  type="button"
                  onClick={() => toggleFaq(idx)}
                  className="w-full flex items-center justify-between text-left text-cream-light select-none focus:outline-none group pr-2 cursor-pointer"
                >
                  <span className="font-serif text-lg md:text-xl font-normal group-hover:text-cream-muted transition-colors">
                    {faq.question}
                  </span>
                  <ChevronDown
                    className={`w-5 h-5 text-cream-muted/60 transform transition-transform duration-200 shrink-0 ml-4 ${
                      isOpen ? "rotate-180 text-cream-light" : ""
                    }`}
                  />
                </button>
                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      exit={{ opacity: 0, height: 0 }}
                      transition={{ duration: 0.25, ease: "easeInOut" }}
                      className="overflow-hidden"
                    >
                      <div className="pt-3 text-sm text-cream-muted/80 leading-relaxed font-sans">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </motion.div>
      </div>
    </section>
  );
}
