"use client";

import React, { useState } from "react";
import { ChevronDown } from "lucide-react";

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    {
      question: "Where do we receive our login credentials?",
      answer:
        "User accounts are pre-generated by organizers. Team IDs and temporary passcodes are distributed physically at the venue before the market opens.",
    },
    {
      question: "What happens if our device disconnects?",
      answer:
        "Portfolio state and balances are synchronized continuously, so reconnecting immediately restores your latest portfolio state with zero lost inventory.",
    },
    {
      question: "Can multiple team members log in simultaneously?",
      answer:
        "Multiple sessions can view the team portfolio, but teams should designate one primary operator to avoid duplicate orders during volatile moments.",
    },
  ];

  const toggleFaq = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section
      className="relative w-full py-24 md:py-32 px-5 sm:px-8 lg:px-12 border-t border-border-brown/40"
      id="faqs"
    >
      <div className="max-w-3xl mx-auto flex flex-col gap-12">
        {/* Section Header */}
        <div className="flex flex-col items-center text-center">
          <h2 className="font-serif text-3xl sm:text-4xl text-cream-light font-normal tracking-tight mb-3">
            Frequently Asked Questions
          </h2>
          <p className="text-cream-muted text-base max-w-md font-normal font-sans">
            Essential operational details for participating teams.
          </p>
        </div>

        {/* Clean Accordion */}
        <div className="divide-y divide-border-brown/40 border-y border-border-brown/40">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div key={faq.question} className="py-5">
                <button
                  type="button"
                  onClick={() => toggleFaq(idx)}
                  className="w-full flex items-center justify-between text-left text-cream-light select-none focus:outline-none group pr-2"
                >
                  <span className="font-serif text-lg md:text-xl font-normal group-hover:text-cream-muted transition-colors">
                    {faq.question}
                  </span>
                  <ChevronDown
                    className={`w-5 h-5 text-cream-muted/60 transform transition-transform duration-200 shrink-0 ml-4 ${
                      isOpen ? "rotate-180 text-cream-light" : ""
                    }`}
                  />
                </button>
                {isOpen && (
                  <div className="pt-3 text-sm text-cream-muted/80 leading-relaxed font-sans animate-fadeIn">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
